### ISSUE TITLE
TextField cannot be imported as RNUILib Package

### ISSUE THREAD

**Issue by bjjeong** [wix/react-native-ui-lib#903] opened 2020-08-18 19:25 UTC
I'm am using `react-native-ui-lib@5.12.4` and currently trying to import the `TextField` component like this: 
```javascript
import { TextField } from 'react-native-ui-lib/inputs';
```
However, I get a `Cannot read property "TextField" of undefined` error. Should I be importing from somewhere else? The component is clearly in `/inputs` as seen [here](https://github.com/wix/react-native-ui-lib/blob/master/src/components/inputs/index.js).

**Comment by davidstott** [comment] 2020-08-20 01:24
A work around is to create a textField.js in root dir of react-native-ui-lib with this code
`module.exports = require('./src/components/inputs/TextField').default;`
can then import like this:
`import TextField from 'react-native-ui-lib/textField';`
Use patch-package to manage this patch.

**Comment by ethanshar** [comment] 2020-08-20 05:11
Hi, 
This is duplicate of #881
And a fix will be released next version

**Closed** 2020-08-20 05:11 UTC
Labels: bug, waiting for release
