### ISSUE TITLE
[Android][KeyboardAccessoryView] Screen flickers when keyboard show

### ISSUE THREAD

**Issue by 000xuandu** [wix/react-native-ui-lib#2063] opened 2022-05-25 03:04 UTC
@M-i-k-e-l M
Please take a look! Thank you.

## Description
As mentioned in the title

### Related to

- [x] KeyboardAccessory
- [x] [Source code](https://github.com/wix/react-native-ui-lib/tree/master/demo/src/screens/nativeComponentScreens/keyboardAccessory
)

### Steps to reproduce
Very simple, just get the code from GitHub and run android
URL: https://github.com/wix/react-native-ui-lib/tree/master/demo/src/screens/nativeComponentScreens/keyboardAccessory

#### Expected behavior
Smooth like iOS (Video attached below)

#### Actual behavior
The screen flickers when the keyboard show

## More Info
I tested it on the android emulator Android 8.1 and the real device Redmi Note 8 Pro (Android 10)

### Screenshots/Video

https://user-images.githubusercontent.com/33916400/170170001-0da8ed9a-7dd0-4155-af6c-c6a9ee93baab.mov

https://user-images.githubusercontent.com/33916400/170170016-ef383ff4-7790-45da-afc5-c923db6396c4.mov

### Environment

- React Native: 0.67.2
- React Native UI Lib: 6.15.2
- @react-native-community/blur: "^3.6.0",
- @react-native-picker/picker: "^2.4.1",
- react-native-reanimated: "^2.8.0",
- react-native-screens: 3.13.1
- react-native-community/netinfo: 8.2.0
- @react-native-community/datetimepicker: 6.1.3
- react-native-gesture-handler: 2.3.0

### Affected platforms

- [x] Android

**Comment by huy-lv** [comment] 2022-05-29 02:27
hope this will be fix soon

**Comment by M-i-k-e-l** [comment] 2022-06-02 12:53
From what I've seen the issue is caused by the fact that we're getting a callback to `onSoftKeyboardVisible` once the keyboard is shown, and only then we "minimize" the custom keyboard, I don't see a way to fix this in the current architecture. I also don't see us making a big change in this component.

So, I'm sorry to say this won't be fixed in the near future.

**Closed by M-i-k-e-l** 2022-06-02 12:53 UTC
Labels: bug

**Comment by 000xuandu** [comment] 2022-07-08 09:46
@M-i-k-e-l 
So does it mean that on android this library is not usable? 
It cannot be used, when the above phenomenon occurs!

**Comment by M-i-k-e-l** [comment] 2022-07-10 05:41
1. It seems that you are seeing a much bigger impact than we do, it could be device specific, have you tested on other devices?
2. At most you have a problem with a specific component, not the library.

**Comment by 000xuandu** [comment] 2022-07-10 05:47
@M-i-k-e-l 
This problem is not just me, but many of my friends also have it.

**Comment by fukemy** [comment] 2022-07-21 09:49
@000xuandu did u tested with release mode?  May be debug mode cause device laggy

**Comment by huuthinh95** [comment] 2022-07-21 11:27
you can try downgrade lib 'react-native-screens' to v2.0.0-alpha.33
