### ISSUE TITLE
How do I disable click for custom renderItem on Picker.Item 

### ISSUE THREAD

**Issue by oiojin831** [wix/react-native-ui-lib#68] opened 2018-01-24 15:54 UTC
How do I disable click for custom renderItem on Picker.Item ?
I am using react-moment to display my datetime. 
I manage to render everything fine but the disabled item.

any suggestion?
Thanks ;D

**Comment by inbalwix** [comment] 2018-02-01 09:50
On your <Picker.Item> item pass 'disabled' prop with the option to disable as it's value (i.e. disabled={option.disabled}). Here is an example:
```
<Picker
            placeholder="Pick a single language"
            value={this.state.language}
            enableModalBlur={false}
            onChange={item => this.setState({language: item})}
            topBarProps={{title: 'Languages'}}
          >
            {_.map(options, option =>
              <Picker.Item
                key={option.value}
                value={option}
                **disabled={option.disabled}**
              />,
            )}
          </Picker>
```
Let me know if that solves you issue.

**Comment by Inbal-Tish** [comment] 2018-04-01 11:00
Hi. Can we close this issue?

**Comment by Dirrsci** [comment] 2018-04-27 18:56
This doesn't work for me. Neither `disabled={true}` nor `enabled={false}` do anything. I'm using version `0.54.0`

**Comment by Inbal-Tish** [comment] 2018-06-07 11:45
@Dirrsci Hi. Can you add a code snippet? 'disabled' is a prop on Picker.Item ('enabled' is not!) that disables the click on the Picker.item (not the whole Picker). See the screenshot for a Picker where we pass the 'disabled' prop to all of its items: 
![simulator screen shot - iphone 6 - 2018-06-07 at 14 43 16](https://user-images.githubusercontent.com/33805983/41097636-5796e774-6a61-11e8-900d-d8970c66bc82.png)

**Comment by joaquinwojcik** [comment] 2019-01-23 23:06
Hmmm, I think that's a only Android problem. Im having the same issue.

Here is my code:
`<Picker.Item key='0' label={field.placeholder} value='default' disabled={true}/>`

Im using React Native 0.57.8.
![select](https://user-images.githubusercontent.com/3205737/51643169-56741580-1f4a-11e9-89a3-85f9ac18601f.jpg)

**Comment by edoantonioco** [comment] 2019-02-06 19:18
I have it like this

` <Picker.Item label="10:00 A.M." value="10" />
<Picker.Item label="11:00 A.M." value="11" />
<Picker.Item disabled={true} label="12:00 A.M." value="12" />
<Picker.Item label="1:00 P.M." value="13" />`

and it doesnt work at all. I still can select 12 pm

**Comment by Inbal-Tish** [comment] 2019-02-10 16:25
@edoantonioco This is my code snippet and it works just fine (12 am is disable and cannot be selected):
```
<Picker
          placeholder="Pick your poison"
          placeholderTextColor={Colors.blue30}
          topBarProps={{title: 'Title'}}
          text70
          red30
          showSearch
        >
          <Picker.Item label="10:00 A.M." value="10"/>
          <Picker.Item label="11:00 A.M." value="11"/>
          <Picker.Item label="12:00 A.M." value="12" disabled/>
          <Picker.Item label="1:00 P.M." value="13"/>
        </Picker>
```
See if that helps you. If not please send more details to reproduce the bug, like which platform, devices, os version etc. so we can nerrow it down to find the issue.

**Comment by mi-mazouz** [comment] 2019-05-17 20:16
Any update? It does not works for me as well!

**Comment by sagarv1997** [comment] 2019-05-27 08:22
> @edoantonioco This is my code snippet and it works just fine (12 am is disable and cannot be selected):
> 
> ```
> <Picker
>           placeholder="Pick your poison"
>           placeholderTextColor={Colors.blue30}
>           topBarProps={{title: 'Title'}}
>           text70
>           red30
>           showSearch
>         >
>           <Picker.Item label="10:00 A.M." value="10"/>
>           <Picker.Item label="11:00 A.M." value="11"/>
>           <Picker.Item label="12:00 A.M." value="12" disabled/>
>           <Picker.Item label="1:00 P.M." value="13"/>
>         </Picker>
> ```
> 
> See if that helps you. If not please send more details to reproduce the bug, like which platform, devices, os version etc. so we can nerrow it down to find the issue.

Not Working

React-native 0.57.8
Platform: Windows
Device: Android
OS Version: 9

**Comment by ethanshar** [comment] 2019-05-29 06:58
Hey, 
did u try running our example project?
there's a demo screen for the picker component 
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/PickerScreen.js
which works great (with the disabled feature) both on iOS and Android.

**Comment by mi-mazouz** [comment] 2019-06-03 14:27
@ethanshar in your project you're using the picker from react-native-ui-lib, that's why it works I guess

**Comment by oborshchak** [comment] 2019-06-04 09:04
Seems like dudes used Picker from 'react-native', not from Wix UI lib - and original Picker haven't `disabled` prop.

**Comment by ethanshar** [comment] 2019-07-07 06:46
closing due inactivity

**Closed by ethanshar** 2019-07-07 06:46 UTC

**Comment by mkhoussid** [comment] 2019-10-10 16:08
```
...other imports
import { Picker } from 'react-native'

      <Picker
        selectedValue={languageChange ?? "0"}
        style={{
          height: 75,
          width: "50%"
        }}
        onValueChange={itemValue =>
          itemValue !== "0" && setLanguageChange(itemValue)
        }
      >
        <Picker.Item label="Select" value="0" />
        <Picker.Item label="English" value="en" />
        <Picker.Item label="Русский" value="ru" />
        <Picker.Item label="中文" value="zh" disabled={true} />
      </Picker>
```
Any idea why this isn't working?

**Comment by GuvanchBayryyyev** [comment] 2019-10-22 16:15
I did not disabled, but I hide the Picker.Item component as following:
`{this.state.loading = false ? (<Picker.Item label="Art" value="Art" />) :null}`

**Comment by mirhat** [comment] 2020-03-04 11:51
I am having this issue also. Disabled prop is not working!

**Comment by rahuldasgupta24** [comment] 2020-10-12 21:00
Tried `disabled={true}` as well as just `disabled` prop. Unfortunetly none works! any undate?

**Comment by ethanshar** [comment] 2020-10-13 04:06
Hi @rahuldasgupta24 
Are you passing `disabled` to the `Picker.Item` or `Picker`? 
You need to pass it to to `Picker.Item` 
There's a working example in the PickerScreen example 
https://github.com/wix/react-native-ui-lib/blob/4c83788365d3de99bbe493bca5725fe4a8e4a32b/demo/src/screens/componentScreens/PickerScreen.js#L104

**Comment by rahuldasgupta24** [comment] 2020-10-13 19:02
> Hi @rahuldasgupta24
> Are you passing `disabled` to the `Picker.Item` or `Picker`?
> You need to pass it to to `Picker.Item`
> There's a working example in the PickerScreen example
> https://github.com/wix/react-native-ui-lib/blob/4c83788365d3de99bbe493bca5725fe4a8e4a32b/demo/src/screens/componentScreens/PickerScreen.js#L104

Thanks @ethanshar! This will help.

**Comment by DaniyalShaikh-0** [comment] 2021-05-31 14:17
Hello Devs Team, i appreciate your help for the react native community. The component is really good but Picker.Item disabled is not working for me aswell, on android. I tried both enabled and disabled. It is now enabled according to your Docs, But does work. It still remains selectable. Can you Help me if possible?

```
           <Picker.Item
              color='purple'
              label='None'
              value='none'
              key='none'
              enabled={true}
              //   fontFamily='arial'
            />
            <Picker.Item
              color='purple'
              label='Olvl'
              value='olvl'
              //   key='Olvl'
              enabled={false}
              //   fontFamily='arial'
            />
            <Picker.Item
              color='purple'
              label='Alvl'
              value='alvl'
              key='Alvl'
              enabled={true}
              //   fontFamily='arial'
            />
```

I tried with .map but didn't work so i thought how about i do it individually.. Didn't work either.

**Comment by ethanshar** [comment] 2021-06-08 10:59
Hi @DaniyalShaikh-0 
You are rendering the component. 
First, the right prop to pass to Picker.Item is `disabled` 

You can see the component docs here
https://wix.github.io/react-native-ui-lib/docs/Picker.Item/

Also, here's a snippet of the code that works for me (both on Android and iOS)
```
<Picker>
  <Picker.Item label="None" value="none" key="none" disabled/>
  <Picker.Item label="Olvl" value="olvl"/>
  <Picker.Item label="Alvl" value="alvl" key="Alvl"/>
</Picker>
```

notice that also the `color` prop doesn't exist for Picker.Item

**Comment by prabhashraman** [comment] 2024-02-10 11:24
In latest react-native-picker/picker you can use **enabled={false}** to show any item as disabled.
Code given below

<Picker>
    <Picker.Item key="ddlSelectNone" enabled={false} color='#c0c0c0' label={'Select Item'} value="" />
<Picker>
