### ISSUE TITLE
Modal crash in iOS app extension

### ISSUE THREAD

**Issue by DEVfancybear** [wix/react-native-ui-lib#1241] opened 2021-03-25 07:37 UTC
I'm seeing my app extension crash on some devices. It launches a `Picker` which appears briefly before the whole thing vanishes. I can't see an explicit error message but I have noticed the message below (which I don't understand). Any ideas?

> ExceptionsManager.js:180 Modal was presented with 0x2 orientations mask but the application only supports 0x18.Add more interface orientations to your app's Info.plist to fix this.NOTE: This will crash in non-dev mode.

**Comment by DEVfancybear** [comment] 2021-03-25 07:41
![Screen Shot 2021-03-25 at 2 40 51 PM](https://user-images.githubusercontent.com/47390684/112436120-2f0e7280-8d78-11eb-9a85-204335f56459.png)

**Comment by ethanshar** [comment] 2021-03-30 05:56
Hey @DEVfancybear 
I'm not sure the issue related to the Picker component but to something with your Android native configuration. 

Just to verify, can you render a simple `Modal` imported from `react-native` (and not `react-native-ui-lib`)
Do you experience the same issue?

**Comment by DEVfancybear** [comment] 2021-04-09 02:39
Key @ethanshar
I only encountered it when using the picker in rn ui lib when my app was lanscape only

![Uploading Screen Shot 2021-04-09 at 9.38.57 AM.png…]()

**Comment by DEVfancybear** [comment] 2021-04-09 02:40
Key @ethanshar
I only encountered it when using the picker in rn ui lib when my app was lanscape only
![Screen Shot 2021-04-09 at 9 38 57 AM](https://user-images.githubusercontent.com/47390684/114120874-93543900-9917-11eb-9f4e-2854ab84ae4f.png)

**Comment by DEVfancybear** [comment] 2021-04-09 02:44
Key @ethanshar
I only encountered it when using the `Picker` in `react-native-ui-lib `ui lib when my app was lanscape only?
![Screen Shot 2021-04-09 at 9 38 57 AM](https://user-images.githubusercontent.com/47390684/114121186-1d9c9d00-9918-11eb-9c6e-5db6cebba0c0.png)

**Comment by DEVfancybear** [comment] 2021-04-09 02:45
Key @ethanshar
I only encountered it when using the `Picker` in `react-native-ui-lib` when my app was lanscape only?
![Screen Shot 2021-04-09 at 9 38 57 AM](https://user-images.githubusercontent.com/47390684/114121311-563c7680-9918-11eb-9c3f-1dcff74f5526.png)

**Comment by DEVfancybear** [comment] 2021-04-09 02:49
Key @ethanshar
I only encountered it when using the `Picker` in `react-native-ui-lib` when my app was landscape only?
![Screen Shot 2021-04-09 at 9 38 57 AM](https://user-images.githubusercontent.com/47390684/114121604-d6fb7280-9918-11eb-833e-0c8d3eaeb937.png)
![Screen Shot 2021-04-09 at 9 49 01 AM](https://user-images.githubusercontent.com/47390684/114121617-dbc02680-9918-11eb-86fd-a783e0b374df.png)

**Comment by ethanshar** [comment] 2021-07-05 10:24
Hi @DEVfancybear 
You are right, I can reproduce the issue. 
But it appears to be related to React Native Modal component, which we use in our Picker (and other components)

You will get this error even when using a Modal directly from react-native. 

Closing this, since it should be resolved in react-native

**Closed by ethanshar** 2021-07-05 10:24 UTC
Labels: bug
