### ISSUE TITLE
Cannot install or test the library, npm install fails

### ISSUE THREAD

**Issue by ivangr1** [wix/react-native-ui-lib#628] opened 2020-01-22 11:42 UTC
I cannot install your library nor try the demo.
I tried to test it on Windows machine with Android virtual device using React Native 0.61.5.
`npm install` outputs this error

```npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-ui-lib@5.1.2 postinstall: 'ln -s -f lib/ReactNativeUiLib.podspec ./'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-ui-lib@5.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It seems there is some issue with `lib/ReactNativeUiLib.podspec`

**Comment by ethanshar** [comment] 2020-02-02 15:54
For some reason post install doesn't work on you machine. maybe because it's windows. 
Unfortunately, I can reproduce this cause it works. 
If you like, you can submit a PR with a fix.

**Comment by ethanshar** [comment] 2020-02-02 16:06
Hey @ivangr1 ,
Looking a little into it, It appears you're working on a window command prompt shell which we don't support. 
I highly recommend moving to a linux shell which you can install on Window (as far as I know)

**Closed by ethanshar** 2020-02-02 16:06 UTC

**Comment by MahefaAbel** [comment] 2020-02-25 20:21
I have this issue too in on windows (powershell and command prompt)

I saw that `npm install --ignore-scripts --save react-native-ui-lib` could ignore this issue (but ignore also the post install)

**Comment by batjko** [comment] 2021-02-13 13:35
> Looking a little into it, It appears you're working on a window command prompt shell which we don't support.
> I highly recommend moving to a linux shell which you can install on Window (as far as I know)

This should really be documented somewhere prominently.

Neither the README nor the installation instructions on the docs site mention _anything at all_ about not supporting windows, or at least listing supported OS's.

Is it on the roadmap?

**Comment by ethanshar** [comment] 2021-02-14 05:56
Hi @batjko 
We actually removed the problematic `postinstall` script. 
The project should run fine on a Windows machine

**Comment by batjko** [comment] 2021-02-14 12:24
> The project should run fine on a Windows machine
I see. Then perhaps my issue is something else, I'll clarify some more details..

**Comment by ethanshar** [comment] 2021-02-14 15:21
If it's a different problem, I suggest opening a different issue
