### ISSUE TITLE
Button onPress function doesn't get called

### ISSUE THREAD

**Issue by omarichatman** [wix/react-native-ui-lib#2582] opened 2023-05-06 22:46 UTC
## Description

When using the Button, when I click the button the function I am passing doesn't get called.

### Related to

- [x] Component - Button

### Steps to reproduce

1. Render a Button component with an onPress property.
2. Click on the button
3. See the function you are passing is not getting called

#### Expected behavior

Function being passed to the onPress is called

#### Actual behavior

Function being passed to the onPress is not called

### Code snippet

```
import React from 'react';
import { Button } from 'react-native-ui-lib';

export default function Welcome({ navigation }: AuthStackScreenProps<'Welcome'>) {

const handleRegisterPress = () => {
   console.log('Register Button Pressed'); // Not called
};

return (
                        <Button 
                            style={styles.button}
                            onPress={() => handleRegisterPress()}
                            color={styles.button.color}
                            backgroundColor={styles.button.backgroundColor}
                            size={styles.button.size}
                            label='Register'
                            fullWidth
                            enableShadow
                        />
    );
};
```

### Environment
Expo on mobile Android device

- React Native version: "react-native": "0.69.9",
- React Native UI Lib version: "react-native-ui-lib": "^6.31.0"

### Affected platforms

- [x] Android - Expo

**Comment by omarichatman** [comment] 2023-05-21 13:41
Not able to repro anymore...

**Comment by trofima** [comment] 2023-06-28 08:57
Closing due to the issue does not reproduce.

**Closed by trofima** 2023-06-28 08:57 UTC
Labels: bug

**Comment by damianbeles** [comment] 2023-08-04 10:26
I reproduced it. Put the button inside a React-Native Modal.
